name: linux

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create Build Environment
        run: |
          sudo apt update
          sudo apt install clang libc++-dev libc++abi-dev
          cmake --build .

      - name: Test
        run: ctest tests/unitTests
        env:
          CTEST_OUTPUT_ON_FAILURE: True
